import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

// customize mantine provider

export const metadata: Metadata = {
  title: "Webline Ads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MantineProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </MantineProvider>
  );
}
