import type { Metadata } from "next";
import { Coiny } from "next/font/google";

import { MantineProvider } from "@mantine/core";

const coiny = Coiny({ subsets: ["latin"], weight: "400" });

// customize mantine provider

export const metadata: Metadata = {
  title: "Webline Ads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MantineProvider>
      <html lang="en">
        <body className={coiny.className}>{children}</body>
      </html>
    </MantineProvider>
  );
}
